# -*- coding: utf-8 -*-
"""Webscraping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11TkuD7R6ldM4TMtsQi5ER2fObVzWhFPK
"""

from bs4 import BeautifulSoup
import urllib.request
import os

url = "https://catalog.umkc.edu/course-offerings/graduate/comp-sci/"
source_code = urllib.request.urlopen(url)
plain_text = source_code
soup = BeautifulSoup(plain_text, "html.parser")

result_tags = soup.find_all('span', {"class": "title"})

with open("hello.txt", "w") as file:
  for result in result_tags:
    file.write(result.text + '\n')